object_labels:
    stars: stars (this work)
    galaxies: galaxies (this work)
    eros_245: EROs, $(i-K) > 2.45$ (this work)
    eros_295: EROs, $(i-K) > 2.95$ (this work)
    drgs: DRGs (this work) #$(J-K)_{AB}$ > 1.34$ 
    sf_gzKs: SF-$gzK$s (this work)
    pe_gzKs: PE-$gzK$s (this work)
    og_eros: OG-EROs
    dg_eros: DG-EROs

colors:
  SA: C0
  EN: C1
  LH: C2
  XM: C3
  combo: k

gtc_colors:
  SA: blues
  EN: oranges
  LH: greens
  XM: reds
  combo: grays

counts:
  K_bright: 16.0
  K_faint: 23.0
  Kbin_width: 0.5
  area_density: 36000 # number of randoms per sq. deg. to estimate area.

correlation_function:
  stars:
    K_limits: [17.0, 18.0, 19.0, 20.0, 21.0, 22.0]
  galaxies:
    K_limits: [17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 22.7]
  eros_245:
    K_limits: [20.2, 20.7, 21.2, 21.7, 22.2, 22.7]
  eros_295:
    K_limits: [20.2, 20.7, 21.2, 21.7, 22.2, 22.7]
  drgs:
    K_limits: [20.7, 21.2, 21.7]
  sf_gzKs:
    K_limits: [20.0, 20.5, 21.0, 21.5, 22.0, 22.5]
  pe_gzKs:
    K_limits: [20.5, 21.0, 21.5, 22.0, 22.5]

  initial_parameters:
    power_law: [1e-3, 0.8]
    exp_law: [1e-1, 10.]
    double_power_law: [1e-3, 1.0, 1e-2, 0.4]
    double_power_law_C: [1e-3, 1.0, 1e-2, 0.4, 0.008]
    broken_power_law: [0.02, 1e-2, 1.5, 0.5]
    fixed_double_power_law: [1e-4, 1e-3]
    power_exp_law: [1e-4, 1.0, 5e-3, 5.]
    trunc_power_exp_law: [1e-2, 1.0, 5e1, 1e-2, 4e0]
    double_trunc_power_law: [1e-2, 1.0, 5e1, 1e-2, 0.0, 4e0]
    double_exp_law: [1e-1, 10., 1e-3, 100.]

  bounds:
    power_exp_law: [[1e-5, 1e-1, 1e-5, 1e-2], [1e+1, 1e+2, 1e+1, 5e+1]]
    double_power_law_C: [[1e-8, 1e-1, 1e-6, 1e-2, 0], [1e+2, 3e+0, 1e+2, 3e+0, inf]]
    trunc_power_exp_law: [[1e-5, 1e-2, 1e-2, 1e-6, 1e-2], [1e+2, 5e+0, 1e+3, 1e+0, 1e+3]]
    double_trunc_power_law: [[0., 0., 0., 0., 0., 0.], [inf]]

  composite_lookup:
    power_exp_law: [power_law, exp_law]
    double_power_law: [power_law, power_law]
    double_power_law_C: [power_law, power_law]
    double_exp_law: [exp_law, exp_law]
    trunc_power_exp_law: [trunc_power_law, exp_law]
    double_trunc_power_law: [trunc_power_law, trunc_power_law]

  parameter_names:
    power_law: [amp, slope]
    exp_law: [amp, cutoff]
    trunc_power_law: [amp, slope, cutoff]    

  composite_n_params:
    power_exp_law: [2, 2]
    double_power_law: [2, 2]
    double_power_law_C: [2, 2]
    trunc_power_exp_law: [3, 2]
    double_trunc_power_law: [3, 3]

zdist:
  K_lim:
    default: 22.7
    eros_245: 22.7
  

zbin_correlation_function:
  K_lim: 22.7
  eros_245:
    z_bins_low:  [0.80, 1.00,  1.15, 1.4]
    z_bins_high: [1.05, 1.15,  1.45, 1.8]
  eros_295:
    z_bins: [0.9, 1.1, 1.3, 1.5] 
    

luminosity_function:
  M_bright: -26.0
  M_faint: -19.0
  absM_bin_width: 0.5

  K_bright: 16.0
  K_faint: 22.7 #2.7

  galaxies:
    z_bins_low:  [  0.20,   0.50,   0.60,   0.80,   1.00,   1.25,   1.50,   1.75]
    z_bins_high: [  0.35,   0.60,   0.80,   1.00,   1.25,   1.50,   1.75,   2.00]
    absM_bright: [-19.00, -18.75, -19.50, -20.00, -20.50, -21.00, -21.50, -21.75]
    absM_faint:  [-30.00, -30.00, -30.00, -30.00, -30.00, -30.00, -30.00, -30.00]

  eros_245:
    z_bins_low:  [  0.50,   0.90,   1.30]
    z_bins_high: [  0.90,   1.30,   1.70]
    absM_bright: [-20.00, -21.00, -21.50]
    absM_faint:  [-30.00, -30.00, -30.00]

  eros_295:
    z_bins_low:  [  0.50,   0.90,   1.30]
    z_bins_high: [  0.90,   1.30,   1.70]
    absM_bright: [-19.00, -20.25, -21.00]
    absM_faint:  [-30.00, -30.00, -30.00]

  sf_gzKs:
    z_bins_low:  [  1.40]
    z_bins_high: [  2.50]
    absM_bright: [-22.00]
    absM_faint:  [-30.00]

  pe_gzKs:
    z_bins_low:  [  1.40]
    z_bins_high: [  2.50]
    absM_bright: [-22.00]
    absM_faint:  [-30.00]

  drgs:
    z_bins_low:  [  0.50,   0.90,   1.30]
    z_bins_high: [  0.90,   1.30,   1.70]
    absM_bright: [-19.00, -20.25, -21.00]
    absM_faint:  [-30.00, -30.00, -30.00]

uvj:
  z_bins_low:  [  0.30,  0.70,   1.10,   1.50,   2.00]
  z_bins_high: [  0.70,  1.10,   1.50,   2.00,   2.50]
  #absM_bright: [-19.00, -18.75, -19.00, -19.50, -20.00, -20.50, -21.25, -21.75]
  #absM_faint:  [-30.00, -30.00, -30.00, -30.00, -30.00, -30.00, -30.00, -30.00]



