###===== dxs basic stuff =====###

ccds: [1, 2, 3, 4] # which ccds in stacks contain the data.

fields: [SA, EN, LH, XM]
field_names: [SA22, ElaisN1, Lockman, XMM-LSS]
field_to_code: {SA22: SA, Lockman: LH, ElaisN1: EN, XMM-LSS: XM}
code_to_field: {SA: SA22, LH: Lockman, EN: ElaisN1, XM: XMM-LSS}
tiles_per_field: {SA: 12, LH: 11, EN: 12, XM: 8}

bands: [J, H, K]
eazy_filter_codes: {J: 263, H: 264, K: 265}

wfcam:
  ccd_sidelength: 0.228 # degrees
  ccd_spacing: 0.215 # degrees

# some error catching?
mosaics:
  border: 100
  max_size: [25000, 25000]
  pixel_scale: 0.2 # arcsec.
  include_deprecated_stacks: True
  masked_bgr_size: 32   # using segmentation map as mask, how large a bgr mesh to use?

field_limits:
  SA: {ra: [332.0, 336.0], dec: [-1.2, 2.0]}
  LH: {ra: [159.0, 165.0], dec: [56.0, 60.0]}
  EN: {ra: [239.0, 247.0], dec: [53.0, 57.0]}
  XM: {ra: [34.0, 38.0], dec: [-5.5, -2.0]}

catalogs:
  # this is NAMING ONLY!! must change apertures in configuration/sextractor/indiv.sex
  apertures: [18, 20, 30, 40]
  # NAMING ONLY!!! must change flux_radii in configuration/sextractor/indiv.sex
  flux_radii: [20, 50, 90]

masks:
  mosaic_extensions:
    "data": ".fits"
    "cov": ".cov.fits"
    "good_cov": ".cov.good_cov.fits"

bright_stars:
  diffraction_spike_angles: [45., 87.5, 135., 177.5] # boxes at each of these angles in degrees.
  # CHECK: angles are measured anti-clockwise in North-Up, East-Left
  region_coefficients:
    # how big should the regions be given the brightness of each star?
    # sizes in PIXELS. mag ranges as upper_bounds.
    # (ie, provide [1, 5,...] for [-inf, 1, 5,...])
    mag_ranges:   [1.,     4.,    6.,    9.,   13.,  15.] # so this is -inf, 1, 3, 5, 11, 13, 15
    box_widths:   [40000., 4000., 1000., 600., 300., 100.] # ie length, in pix.
    box_heights:  [500.,   40.,   20.,   20.,  10.,  10.] # ie thickness, in pix.
    circle_radii: [4000.,  1500., 200.,  100., 60.,  30.] # in pix.

    # There is a "hand-built" table in ./configuration/very_bright_stars.csv

  stacks:
    # stack stars in these ranges to look at how big 
    # the diffraction spike mask should be.
    mag_ranges:   [5.,  7.,  9.,  11., 13., 15., 17.,]
    cutout_sizes: [600, 600, 200, 200, 100, 100]

merge:
  tile_merge_error: 0.8 # ie, finding repeated objects at the edge of images.
  nir_match_error: 1.0 #
  panstarrs_match_error: 1.0
  cfhtls_match_error: 1.0
  unwise_match_error: 1.0
  hsc_match_error: 1.0
  swire_match_error: 1.0
  galex_match_error: 2.0
  irac_match_error: 1.0

  default_code: 0 # so default merged catalogs will be called FF00K.cat.fits
  default_tiles:
    EN: [1,2,3,4,5,6,7,8,9,10,11,12]
    SA: [1,2,3,4,5,6,7,8,9,10,11,12]
    LH: [1,2,3,4,5,6,7,8,9,10,11]
    XM: [1,2,3,5] # 4,6,7,8 have no J-band.
  

help:
  ccds: "HDU[ii], ii are indexes in stacks which contain data - ie, in DXS, hdu 0 is only a header..."
  field_limits: "a 'square' which vaguely contains all of the data."
  ab_vega_offset: "offset defined such that m_Ab = m_Vega + offset"
  zeropoint_flux: "Flux Fv is Fv0*10**(-m_Vega/2.5). Fv0 should be in Jy!!"

###====== photometry stuff ======###

ab_vega_offset:
  g: -0.08
  r: 0.16
  i: 0.39
  z: 0.54
  y: 0.634
  J: 0.938
  H: 1.39
  K: 1.900
  W1: 2.699 # https://catalog.unwise.me/catalogs.html#bandmerged 
  W2: 3.339
  I1: 2.820
  I2: 3.290

zeropoint_flux:
  J: 1530.0
  H: 1019.0
  K: 631.0
  w1: 309.54
  w2: 171.79
  I1: null
  I2: null

extinction_coeffs:
  g: 3.613
  r: 2.585
  i: 1.908
  z: 1.499
  y: 1.251
  J: 0.902
  H: 0.576
  K: 0.367

###===== external catalogs =====###

external_catalogs: [panstarrs, hsc, swire, unwise, galex, uds, spuds, galex]

external_order:
  galex: 0
  panstarrs: 1
  hsc: 1
  swire: 2
  irac: 2
  spuds: 2
  mips: 3 # unlikely to need/use!


panstarrs:
  fields: [md01, md05, md08, md09]
  # arxiv.org/pdf/1612.05560.pdf --table7 (p18)
  from_dxs_field: {SA: md09, LH: md05, EN: md08, XM: md01}
  bands: [g, r, i, z, y]
  ab_to_vega: {g: -0.08, r: 0.16, i: 0.37, z: 0.54, y: 0.634}
  apertures: [1.04, 1.76, 3.00, 4.64, 7.44, 11.42, 18.20, 28.20, 44.22 ]
  eazy_filter_codes: {g: 334, r: 335, i: 336, z: 337, y: 338}

  # panstarrs https://iopscience.iop.org/article/10.1088/0004-637X/750/2/99/pdf
  # each also has a term depending on (g-i) of the order ~0.01*(g-i) - ignore these...?
  extinction_coeffs:
    g: 3.613
    r: 2.585
    i: 1.908
    z: 1.499
    y: 1.251

  zeropoint_flux:
    g: 3991.0
    r: 3174.0
    i: 2593.0
    z: 2232.0
    y: 2026.0

hsc:
  bands: [g, r, i, z, y]
  eazy_filter_codes: {g: 314, r: 315, i: 316, z: 317, y: 318}
  mask_tar_url: https://hsc-release.mtk.nao.ac.jp/rsrc/S18A_starmask.tar.xz
  url_base: https://hsc-release.mtk.nao.ac.jp/datasearch/catalog_jobs/download/
  catalog_urls:
    EN: 5d5dfc1ea6a3b7e7be2a3afdb08f743bb731c84c106c345607dc936291d45698
    # v-old-- a9a96aae788859825c8f0e6e19ba17165c18ab2f84c51756d3fc92e7c24cae86
    # vv-old-- d8ca24dfb64dc33557f3038373acfede8a85a97933c5b11bb05b5186d3cd6d26
    SA: 0f6f64e0b298553222e58722717ad24f85a2f39ea73a2374785ab9c7506fbdf9
    # v-old-- ba60da052f0c101b858a1b2a794b947e35052dc49f0db0f6d482f3a85fb9fd72
    # vv-old-- 9c9e995238899a5ab2a81cf14266d9e3b43c37c41c69c7c9c3193726410dc146
    XM: 748b2afe2181970c4f97e8f8baa5aa7ff3c57ace81c20c1a28e431eb31e2c4ba
    # v-old-- 871536aa4d6f317e89553702ad3c430f873bd1fe981276df58bcd614ee424200
    # vv-old-- e4d4cc1c21143ade10035b15b1ce4f6fa0b51eec45ab2cb3cf563f7fbb2343a9
    
  random_urls:
    EN: ccb073e381e7643eef7390f532741ece38b7e56f508a89b4dc405a48d17dbc4d
    SA: 626a3d1595e23e9df28ab88a562dfb2865c4baa21b9c62ac7f0e664e0b687088
    XM: d16b422d1eeec0e9ef76bab3140a74e71668320559e7ac8acd9992bbbf0bb1e1
    # old-- 20d07c80836a7006d1cf64ad99f410ab29e160d4c3b34de5c84bb234e7ebee1f

  # https://hsc.mtk.nao.ac.jp/pipedoc/pipedoc_8_e/colorterms.html
  extinction_coeffs:
    g: 3.238
    r: 2.280
    i: 1.641
    z: 1.262
    y: 1.074

swire:
  bands: [I1, I2, I3, I4]
  eazy_filter_codes: {I1: 18, I2: 19, I3: 20, I4: 21}
  url_base: "https://irsa.ipac.caltech.edu/cgi-bin/Gator/nph-query?"
  field_lookup: {EN: elaisn1, XM: xmm, LH: lockman}
  select_columns: [
    "cntr", "object", "ra", "dec",
    "flux_ap3_36", "uncf_ap3_36", "flux_kr_36", "uncf_kr_36",
    "flux_ap3_45", "uncf_ap3_45", "flux_kr_45", "uncf_kr_45",
    "flux_ap3_58", "uncf_ap3_58", "flux_kr_58", "uncf_kr_58",
    "flux_ap3_80", "uncf_ap3_80", "flux_kr_80", "uncf_kr_80",
  ]

  bulk_image_download_urls:
    EN: https://irsa.ipac.caltech.edu/workspace/TMP_QxZ4ok_4562/Atlas/242.75498_55.028390_eq_25053.v0001//wget_data.bat
    XM: https://irsa.ipac.caltech.edu/workspace/TMP_QxZ4ok_4562/Atlas/35.3295_-4.49945_eq_1818.v0001//wget_data.bat
    LH: https://irsa.ipac.caltech.edu/workspace/TMP_QxZ4ok_4562/Atlas/161.29286_57.94361_eq_31102.v0001//wget_data.bat

unwise:
  bands: [W1, W2]
  eazy_filter_codes: {W1: 244, W2: 245}

uds:
  bands: [J, H, K]
  catalog_url: http://pleiades.nottingham.ac.uk/UDS/DR11/UDS_DR11_JHK_rawweight.cat.fits
  image_urls:
    J: http://pleiades.nottingham.ac.uk/UDS/DR11/UDS-DR11-J_bin2x2.mef.fits
    H: http://pleiades.nottingham.ac.uk/UDS/DR11/UDS-DR11-H_bin2x2.mef.fits
    K: http://pleiades.nottingham.ac.uk/UDS/DR11/UDS-DR11-K_bin2x2.mef.fits
  
  # https://pleiades.nottingham.ac.uk/UDS/DR11/UDS-DR11.sex
  phot_apertures: [5.2,7.5,11.2,14.9,22.4,29.8,37.3,178.8376]
  eazy_filter_codes: {J: 263, H: 264, K: 265}


spuds:
  base_url: "https://irsa.ipac.caltech.edu/cgi-bin/Gator/nph-query?"
  bands: [I1, I2, I3, I4]
  eazy_filter_codes: {I1: 18, I2: 19, I3: 20, I4: 21}
  url_base: "https://irsa.ipac.caltech.edu/cgi-bin/Gator/nph-query?"
  select_columns: [
    "cntr", "ra", "dec",
    "flux_ap_36", "uncf_ap_36", 
    "flux_ap_45", "uncf_ap_45",
    "flux_ap_56", "uncf_ap_56",
    "flux_ap_80", "uncf_ap_80",
  ]


galex:
  bands: [fuv, nuv]
  base_url: http://galex.stsci.edu/data/
  img_table_url: http://skyservice.pha.jhu.edu/CasJobsOutput/FITS/galex_img_asedgewick.fit
  catalog_stem: combo_catalog
  eazy_filter_codes: {fuv: 120, nuv: 121}

  extinction_coeffs:
  # GALEX https://ui.adsabs.harvard.edu/abs/2019MNRAS.489.5046W/abstract
    fuv: 8.01
    nuv: 6.79 


video:
    vertices_file:
        # relative to base_path
        XM: "external/video/XM_vertices.yaml"

veils:
    vertices_file:
        # relative to base_path
        XM: "external/veils/XM_vertices.yaml"

