###===== dxs basic stuff =====###

ccds: [1, 2, 3, 4] # which ccds in stacks contain the data.

field_names: [SA22, Lockman, ElaisN1, XMM-LSS]
field_to_code: {SA22: SA, Lockman: LH, ElaisN1: EN, XMM-LSS: XM}
code_to_field: {SA: SA22, LH: Lockman, EN: ElaisN1, XM: XMM-LSS}
tiles_per_field: {SA: 12, LH: 11, EN: 12, XM: 8}

wfcam:
  ccd_sidelength: 0.228 # degrees
  ccd_spacing: 0.215 # degrees

# some error catching?
mosaics:
  border: 100
  max_size: [25000,25000]
  pixel_scale: 0.2 # arcsec.

field_limits:
  SA: {ra: [333.0, 336.0], dec: [-1.2, 2.0]}
  LH: {ra: [159.0, 165.0], dec: [56.0, 60.0]}
  EN: {ra: [239.0, 247.0], dec: [53.0, 57.0]}
  XM: {ra: [34.0, 38.0], dec: [-5.5, -2.0]}

#catalogs:

masks:
  mosaic_extensions:
    "data": ".fits"
    "cov": ".cov.fits"
    "good_cov": ".cov.good_cov.fits"

bright_stars:
  diffraction_spike_angles: [45., 87.5, 135., 177.5] # boxes at each of these angles in degrees.
  region_coefficients:
    # assume the all start at 0 or the previous mag?
    mag_ranges: [5., 11., 13., 15.]
    box_widths: [1000., 600., 300., 100.] # in pix.
    box_heights: [20., 20., 10., 10.] # in pix.
    circle_radii: [200., 100., 60., 30.] # in pix.

  stacks:
    mag_ranges: [0., 7., 8., 9., 10., 11., 12., 13., 14., 15., 16., 17.]

help:
  ccds: "ccds idxs in stacks which contain data - ie, in DXS, hdu 0 is only a header..."
  field_limits: "a 'square' which vaguely contains all of the data."
  ab_vega_offset: "offset defined such that m_Ab = m_Vega + offset"
  zeropoint_flux: "Flux Fv is Fv0*10**(-m_Vega/2.5). Fv0 should be in Jy!!"

###====== photometry stuff ======###

ab_vega_offset:
  g: -0.08
  z: 0.16
  i: 0.39
  z: 0.54
  y: 0.634
  J: 0.938
  H: 1.39
  K: 1.85
  W1: 2.699 # https://catalog.unwise.me/catalogs.html#bandmerged 
  W2: 3.339
  "[3.6]": 2.820
  "[4.5]": 3.290

zeropoint_flux:
  g: 3991.0
  z: 3174.0
  i: 2593.0
  z: 2232.0
  y: 2026.0
  J: 1530.0
  H: 1019.0
  K: 631.0
  w1: 309.54
  w2: 171.79
  "[3.6]": "NONE"
  "[4.5]": "NONE"
  
wavelengths:
  g: 475.0
  r: 622.0
  i: 763.0
  z: 905.0 
  y: 1005.0
  J: 1248.0
  H: 1631.0
  K: 2201.0
  w1: 3368.0
  w2: 4618.0
  "[3.6]": 3600.0
  "[4.5]": 4500.0


###===== external catalogs =====###

# arxiv.org/pdf/1612.05560.pdf --table7 (p18)
panstarrs:
  fields: [md01, md05, md08, md09]
  from_dxs_field: {SA: md09, LH: md05, EN: md08, XM: md01}
  bands: [g, r, i, z, y]

  ab_to_vega: {g: -0.08, r: 0.16, i: 0.37, z: 0.54, y: 0.634}
  apertures: [1.04, 1.76, 3.00, 4.64, 7.44, 11.42, 18.20, 28.20, 44.22 ]

hsc:
  mask_tar_url: https://hsc-release.mtk.nao.ac.jp/rsrc/S18A_starmask.tar.xz
  url_base: https://hsc-release.mtk.nao.ac.jp/datasearch/catalog_jobs/download/
  catalog_urls:
    EN: d8ca24dfb64dc33557f3038373acfede8a85a97933c5b11bb05b5186d3cd6d26
    SA: 9c9e995238899a5ab2a81cf14266d9e3b43c37c41c69c7c9c3193726410dc146
    # XM: 









