# system
scheduler: slurm
account: durham
queue: cosma
cpus_per_node: 16
max_time: 0-12:00:00
email: False

extra_header_lines: []
    
modules: # load everything. order is purge, load, source, extra.
  purge: # commands to clear the system.
    - module purge
  modules_to_load:
    - python/3.6.5
    - sextractor/2.19.5
    - swarp/2.38
    - java/jdk1.8.0_181 # for java
    - cosma/2018 # for stilts
  modules_to_source:
    # also include your python env.
    - /cosma/home/durham/dc-sedg2/dxsenv/bin/activate
  # extra: # also inlcude "module load", "source" or whatever the prefix is.
    
