
base_dir: "/cosma5/data/durham/dc-sedg2/dxs/"
python_script_path: "@base_dir/dxs/pipelines/mosaic_pipeline.py" # required!
run_name: "LH_mosaics_210312"# required! meaningful name...

args:
    fields: LH
    tiles: 7
    band: K
    
kwargs:
    n_cpus: 16
    coverage: None
    masked: None
