
base_dir: "/cosma5/data/durham/dc-sedg2/dxs/"
python_script_path: "@base_dir/dxs/pipelines/main_pipeline.py" # required!
run_name: "LH_main_$date"# required! meaningful name...
job_name: "lh"

args:
    fields: LH
    tiles: 1-11
    
kwargs:
    n_cpus: 16
