
base_dir: "/cosma5/data/durham/dc-sedg2/dxs/"
python_script_path: "@base_dir/scripts/basic_pipeline.py" # required!
run_name: SA_catalogs_210216 # required! meaningful name...

args:
    fields: SA
    tiles: 1-12
    #bands: J,K # Don't need to specify.
    
kwargs:
    n_cpus: 16    
    full: None
