
base_dir: "/cosma5/data/durham/dc-sedg2/dxs/"
python_script_path: "@base_dir/dxs/pipelines/main_pipeline.py" # required!
run_name: "SA_main_210331"# required! meaningful name...
job_name: "sa"

args:
    fields: SA
    tiles: 1-12
    
kwargs:
    n_cpus: 16
